---
- name: Add Neovim PPA (Ubuntu)
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  when: ansible_os_family == "Debian"

- name: Install Neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Install VS Code via Flatpak
  community.general.flatpak:
    name: com.visualstudio.code
    state: present
    method: user
    remote: flathub
