---
- name: Install Neovim
  become: true
  ansible.builtin.dnf:
    name: neovim
    state: present

- name: Install VS Code via Flatpak
  community.general.flatpak:
    name: com.visualstudio.code
    state: present
    method: user
    remote: flathub
