---
- name: Ensure Flathub remote is configured
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present

- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
    remote: flathub
  loop:
    - com.visualstudio.code
    - com.rtosta.zapzap
